#!/usr/bin/env python3
"""
Curated lexicon dataset for English and Bahasa Melayu to Chinese translations.
Provides rich, essential vocabulary for offline dictionary lookup.
Expanded in v1.0.1 with Malaysian colloquial terms, daily vocabulary, idioms and phrases.
"""

def get_curated_ms_words():
    """
    Returns rich Malay-Chinese vocabulary covering core roots, daily life, work, travel,
    grammar, numbers, food, places, and affixed forms.
    """
    ms_list = [
        # Common greetings & fundamentals
        {"word": "selamat", "pos": "adj./n.", "phonetic": "sə-la-mat", "definition": "平安；安全；恭祝", "example": "Selamat pagi! (早上好！)"},
        {"word": "selamat pagi", "pos": "phr.", "phonetic": "sə-la-mat pa-gi", "definition": "早上好，早安", "example": "Selamat pagi, cikgu."},
        {"word": "selamat tengah hari", "pos": "phr.", "phonetic": "", "definition": "中午好，午安", "example": ""},
        {"word": "selamat petang", "pos": "phr.", "phonetic": "", "definition": "下午好，傍晚好", "example": ""},
        {"word": "selamat malam", "pos": "phr.", "phonetic": "", "definition": "晚安", "example": ""},
        {"word": "selamat datang", "pos": "phr.", "phonetic": "", "definition": "欢迎光临", "example": "Selamat datang ke Malaysia."},
        {"word": "selamat jalan", "pos": "phr.", "phonetic": "", "definition": "一路顺风，再见", "example": ""},
        {"word": "selamat tinggal", "pos": "phr.", "phonetic": "", "definition": "再见（留者对去者说）", "example": ""},
        {"word": "terima kasih", "pos": "phr.", "phonetic": "tə-ri-ma ka-seh", "definition": "谢谢，感谢", "example": "Terima kasih banyak-banyak."},
        {"word": "sama-sama", "pos": "phr.", "phonetic": "sa-ma sa-ma", "definition": "不客气，不用谢", "example": ""},
        {"word": "tolong", "pos": "v./n.", "phonetic": "to-long", "definition": "帮助，帮忙；请", "example": "Tolong saya. (请帮帮我。)"},
        {"word": "menolong", "pos": "v.", "phonetic": "mə-no-long", "definition": "帮助，援助", "example": "Dia suka menolong orang."},
        {"word": "pertolongan", "pos": "n.", "phonetic": "pər-to-long-an", "definition": "帮助，救助", "example": ""},
        {"word": "maaf", "pos": "n./v.", "phonetic": "ma-af", "definition": "对不起，抱歉；原谅", "example": "Minta maaf."},
        {"word": "memaafkan", "pos": "v.", "phonetic": "mə-ma-af-kan", "definition": "原谅，宽恕", "example": ""},
        {"word": "khabar", "pos": "n.", "phonetic": "kha-bar", "definition": "消息，音讯", "example": "Apa khabar? (你好吗？)"},
        {"word": "apa khabar", "pos": "phr.", "phonetic": "a-pa kha-bar", "definition": "你好吗？近况如何？", "example": "Khabar baik. (我很好。)"},

        # Malaysian Daily & Colloquialisms (Tapau, Lepak, Mamak, etc.)
        {"word": "tapau", "pos": "v./n.", "phonetic": "ta-pao", "definition": "打包，带走（食物外带）", "example": "Makan sini atau tapau? (堂食还是打包？)"},
        {"word": "bungkus", "pos": "v./n.", "phonetic": "bung-kus", "definition": "打包，包裹", "example": "Nasi lemak satu, bungkus ya."},
        {"word": "lepak", "pos": "v.", "phonetic": "le-pak", "definition": "闲逛，聚会闲聊，消磨时间", "example": "Jom lepak mamak! (去印度煎饼店喝茶闲聊！)"},
        {"word": "mamak", "pos": "n.", "phonetic": "ma-mak", "definition": "印度裔穆斯林餐馆/档口", "example": "Kedai mamak buka 24 jam."},
        {"word": "jom", "pos": "int.", "phonetic": "jom", "definition": "走吧，一起来吧（邀约俚语）", "example": "Jom makan! (走，吃饭去！)"},
        {"word": "kantoi", "pos": "v./adj.", "phonetic": "kan-toi", "definition": "穿帮，被抓现行，露馅", "example": "Dia kantoi curi tulang."},
        {"word": "cun", "pos": "adj.", "phonetic": "chun", "definition": "漂亮，棒，正好，完美", "example": "Baju ini memang cun! (这件衣服真漂亮！)"},
        {"word": "gempak", "pos": "adj.", "phonetic": "gəm-pak", "definition": "厉害，震撼，炫酷", "example": "Persembahan yang sangat gempak."},
        {"word": "padu", "pos": "adj.", "phonetic": "pa-du", "definition": "扎实，强劲，绝赞，美味", "example": "Sambal dia memang padu!"},
        {"word": "mantap", "pos": "adj.", "phonetic": "man-tap", "definition": "稳固；棒极了，优秀", "example": "Kerja yang mantap!"},
        {"word": "syok", "pos": "adj.", "phonetic": "shok", "definition": "爽快，过瘾，很享受", "example": "Syok sendiri (自嗨), Syok sangat!"},
        {"word": "belanja", "pos": "v./n.", "phonetic": "bə-lan-ja", "definition": "请客；开销，消费", "example": "Hari ini saya belanja. (今天我请客。)"},
        {"word": "potong", "pos": "v.", "phonetic": "po-tong", "definition": "剪，切，削减；超车", "example": "potong gaji (扣薪水), potong rambut (理发)"},
        {"word": "potong stim", "pos": "phr.", "phonetic": "", "definition": "扫兴，败兴", "example": "Janganlah potong stim."},
        {"word": "angpau", "pos": "n.", "phonetic": "ang-pao", "definition": "红包", "example": "Dapat angpau sempena Tahun Baharu Cina."},
        {"word": "rojak", "pos": "n./adj.", "phonetic": "ro-jak", "definition": "罗惹（马来杂拌沙拉）；混合的，杂糅的", "example": "Bahasa rojak (混合语言)"},
        {"word": "cendol", "pos": "n.", "phonetic": "chen-dol", "definition": "珍多冰（马来传统甜品）", "example": ""},
        {"word": "nasi lemak", "pos": "n.", "phonetic": "na-si lə-mak", "definition": "椰浆饭（马来西亚国民美食）", "example": ""},
        {"word": "roti canai", "pos": "n.", "phonetic": "ro-ti cha-nai", "definition": "印度飞饼，印度煎饼", "example": ""},
        {"word": "teh tarik", "pos": "n.", "phonetic": "teh ta-rek", "definition": "拉茶", "example": "Minum teh tarik kurang manis."},
        {"word": "kopi o", "pos": "n.", "phonetic": "ko-pi o", "definition": "黑咖啡（加糖无奶）", "example": ""},
        {"word": "kopi c", "pos": "n.", "phonetic": "ko-pi si", "definition": "咖啡加淡奶和糖", "example": ""},
        {"word": "ais", "pos": "n.", "phonetic": "ais", "definition": "冰，冰块", "example": "Milo ais (冰美禄)"},
        {"word": "panas", "pos": "adj.", "phonetic": "pa-nas", "definition": "热的", "example": "Teh panas (热茶)"},
        {"word": "kurang manis", "pos": "phr.", "phonetic": "", "definition": "少糖，微甜", "example": "Kopi satu, kurang manis ya."},

        # Pronouns
        {"word": "saya", "pos": "pron.", "phonetic": "sa-ya", "definition": "我（礼貌/正式）", "example": "Saya orang Malaysia."},
        {"word": "aku", "pos": "pron.", "phonetic": "a-ku", "definition": "我（熟人/口语）", "example": ""},
        {"word": "anda", "pos": "pron.", "phonetic": "an-da", "definition": "您，你（礼貌）", "example": ""},
        {"word": "awak", "pos": "pron.", "phonetic": "a-wak", "definition": "你（常用）", "example": "Awak nak pergi mana?"},
        {"word": "kamu", "pos": "pron.", "phonetic": "ka-mu", "definition": "你，你们", "example": ""},
        {"word": "dia", "pos": "pron.", "phonetic": "di-a", "definition": "他，她", "example": "Dia kawan saya."},
        {"word": "beliau", "pos": "pron.", "phonetic": "bə-li-au", "definition": "他/她（尊称，长辈或领导）", "example": ""},
        {"word": "mereka", "pos": "pron.", "phonetic": "mə-re-ka", "definition": "他们，她们", "example": ""},
        {"word": "kami", "pos": "pron.", "phonetic": "ka-mi", "definition": "我们（不包括对方）", "example": ""},
        {"word": "kita", "pos": "pron.", "phonetic": "ki-ta", "definition": "我们（包括对方）", "example": "Kita satu bangsa."},
        {"word": "ini", "pos": "pron./det.", "phonetic": "i-ni", "definition": "这，这个", "example": "Apa ini? (这是什么？)"},
        {"word": "itu", "pos": "pron./det.", "phonetic": "i-tu", "definition": "那，那个", "example": "Buku itu."},
        {"word": "sini", "pos": "n./adv.", "phonetic": "si-ni", "definition": "这里，这儿", "example": "Di sini."},
        {"word": "sana", "pos": "n./adv.", "phonetic": "sa-na", "definition": "那里，那儿（较远）", "example": "Di sana."},
        {"word": "situ", "pos": "n./adv.", "phonetic": "si-tu", "definition": "那里（中等距离）", "example": ""},

        # Question words
        {"word": "apa", "pos": "pron.", "phonetic": "a-pa", "definition": "什么", "example": "Apa nama awak?"},
        {"word": "siapa", "pos": "pron.", "phonetic": "si-a-pa", "definition": "谁", "example": "Siapa dia?"},
        {"word": "mana", "pos": "pron./adv.", "phonetic": "ma-na", "definition": "哪，哪里", "example": "Di mana tandas?"},
        {"word": "di mana", "pos": "phr.", "phonetic": "di ma-na", "definition": "在哪里", "example": "Di mana stesen kereta api?"},
        {"word": "bila", "pos": "adv./conj.", "phonetic": "bi-la", "definition": "什么时候，何时；当...时", "example": "Bila awak datang?"},
        {"word": "mengapa", "pos": "adv.", "phonetic": "mə-nga-pa", "definition": "为什么，为何", "example": ""},
        {"word": "kenapa", "pos": "adv.", "phonetic": "kə-na-pa", "definition": "为什么（口语）", "example": "Kenapa lambat?"},
        {"word": "bagaimana", "pos": "adv.", "phonetic": "ba-gai-ma-na", "definition": "如何，怎样", "example": "Bagaimana pergi ke sana?"},
        {"word": "berapa", "pos": "pron./adv.", "phonetic": "bə-ra-pa", "definition": "多少（价格/数量）", "example": "Berapa harga ini? (这个多少钱？)"},

        # Homographs
        {"word": "air", "pos": "n.", "phonetic": "a-yer", "definition": "水；液体；饮料", "example": "air kosong (白开水), air batu (冰块)"},
        {"word": "air kelapa", "pos": "n.", "phonetic": "", "definition": "椰子水", "example": ""},
        {"word": "air batu", "pos": "n.", "phonetic": "", "definition": "冰块", "example": ""},
        {"word": "bakar", "pos": "v.", "phonetic": "ba-kar", "definition": "烤，烧，焚烧", "example": "ikan bakar (烤鱼)"},
        {"word": "membakar", "pos": "v.", "phonetic": "məm-ba-kar", "definition": "燃烧，烘烤", "example": ""},
        {"word": "terbakar", "pos": "adj./v.", "phonetic": "tər-ba-kar", "definition": "着火的；被烧伤的", "example": ""},
        {"word": "goreng", "pos": "v./adj.", "phonetic": "go-reng", "definition": "炒，油炸", "example": "nasi goreng (炒饭), mee goreng (炒面)"},
        {"word": "menggoreng", "pos": "v.", "phonetic": "məng-go-reng", "definition": "油炸，炒（动词）", "example": ""},

        # Essential Verbs & Stem Forms
        {"word": "makan", "pos": "v./n.", "phonetic": "ma-kan", "definition": "吃；用餐", "example": "Sudah makan? (吃饱了吗？)"},
        {"word": "memakan", "pos": "v.", "phonetic": "mə-ma-kan", "definition": "吃，吞噬；消耗", "example": ""},
        {"word": "makanan", "pos": "n.", "phonetic": "ma-kan-an", "definition": "食物，食品", "example": "makanan sedap (美味的食物)"},
        {"word": "pemakan", "pos": "n.", "phonetic": "pə-ma-kan", "definition": "食用者；进食用具", "example": ""},
        {"word": "termakan", "pos": "v.", "phonetic": "tər-ma-kan", "definition": "误食，无意中吃了", "example": ""},

        {"word": "minum", "pos": "v.", "phonetic": "mi-num", "definition": "喝，饮", "example": "Minum air. (喝水。)"},
        {"word": "meminum", "pos": "v.", "phonetic": "mə-mi-num", "definition": "饮用", "example": ""},
        {"word": "minuman", "pos": "n.", "phonetic": "mi-num-an", "definition": "饮料", "example": "minuman sejuk (冷饮)"},
        {"word": "peminum", "pos": "n.", "phonetic": "pə-mi-num", "definition": "饮酒者，喝水者", "example": ""},

        {"word": "jalan", "pos": "n./v.", "phonetic": "ja-lan", "definition": "路，街道；行走，前进", "example": "jalan raya (大马路)"},
        {"word": "berjalan", "pos": "v.", "phonetic": "bər-ja-lan", "definition": "步行，走路；运转", "example": "berjalan kaki (步行)"},
        {"word": "menjalankan", "pos": "v.", "phonetic": "mən-ja-lan-kan", "definition": "执行，开动，实行", "example": "menjalankan tugas"},
        {"word": "perjalanan", "pos": "n.", "phonetic": "pər-ja-lan-an", "definition": "旅程，旅途", "example": "Selamat perjalanan!"},

        {"word": "baca", "pos": "v.", "phonetic": "ba-ca", "definition": "读，阅读", "example": "baca buku (读书)"},
        {"word": "membaca", "pos": "v.", "phonetic": "məm-ba-ca", "definition": "阅读，朗读", "example": "Saya suka membaca buku."},
        {"word": "bacaan", "pos": "n.", "phonetic": "ba-ca-an", "definition": "读物；读数", "example": ""},
        {"word": "pembaca", "pos": "n.", "phonetic": "pəm-ba-ca", "definition": "读者", "example": ""},

        {"word": "tulis", "pos": "v.", "phonetic": "tu-lis", "definition": "写，书写", "example": "tulis surat (写信)"},
        {"word": "menulis", "pos": "v.", "phonetic": "mə-nu-lis", "definition": "写作，书写", "example": "Dia sedang menulis."},
        {"word": "tulisan", "pos": "n.", "phonetic": "tu-lis-an", "definition": "笔迹，文字，文章", "example": ""},
        {"word": "penulis", "pos": "n.", "phonetic": "pə-nu-lis", "definition": "作者，作家", "example": ""},

        {"word": "sapu", "pos": "v./n.", "phonetic": "sa-pu", "definition": "扫；涂抹；扫帚", "example": "sapu tangan (手帕)"},
        {"word": "menyapu", "pos": "v.", "phonetic": "mə-nya-pu", "definition": "扫地；涂刷", "example": "menyapu lantai (扫地)"},
        {"word": "penyapu", "pos": "n.", "phonetic": "pə-nya-pu", "definition": "扫帚", "example": ""},

        {"word": "pilih", "pos": "v.", "phonetic": "pi-leh", "definition": "选择，挑选", "example": ""},
        {"word": "memilih", "pos": "v.", "phonetic": "mə-mi-leh", "definition": "挑选，选举", "example": ""},
        {"word": "pilihan", "pos": "n.", "phonetic": "pi-lih-an", "definition": "选择，选项", "example": "pilihan raya (大选)"},
        {"word": "pemilihan", "pos": "n.", "phonetic": "pə-mi-lih-an", "definition": "选举，选拔", "example": ""},

        {"word": "beli", "pos": "v.", "phonetic": "bə-li", "definition": "买，购买", "example": "beli barang (买东西)"},
        {"word": "membeli", "pos": "v.", "phonetic": "məm-bə-li", "definition": "购买，买进", "example": ""},
        {"word": "belian", "pos": "n.", "phonetic": "bə-li-an", "definition": "购买之物", "example": ""},
        {"word": "pembeli", "pos": "n.", "phonetic": "pəm-bə-li", "definition": "买家，顾客", "example": ""},
        {"word": "pembelian", "pos": "n.", "phonetic": "pəm-bə-li-an", "definition": "采购，购买", "example": ""},

        {"word": "jual", "pos": "v.", "phonetic": "ju-al", "definition": "卖，出售", "example": ""},
        {"word": "menjual", "pos": "v.", "phonetic": "mən-ju-al", "definition": "销售，卖", "example": ""},
        {"word": "jualan", "pos": "n.", "phonetic": "ju-al-an", "definition": "销售额；减价促销", "example": "jualan murah (大减价)"},
        {"word": "penjual", "pos": "n.", "phonetic": "pən-ju-al", "definition": "卖家，售货员", "example": ""},

        {"word": "ajar", "pos": "v.", "phonetic": "a-jar", "definition": "教，教育", "example": ""},
        {"word": "mengajar", "pos": "v.", "phonetic": "mə-nga-jar", "definition": "教导，讲课", "example": "Cikgu mengajar bahasa."},
        {"word": "belajar", "pos": "v.", "phonetic": "bə-la-jar", "definition": "学习", "example": "Saya belajar bahasa Melayu."},
        {"word": "pelajar", "pos": "n.", "phonetic": "pə-la-jar", "definition": "学生", "example": ""},
        {"word": "pengajar", "pos": "n.", "phonetic": "pə-nga-jar", "definition": "导师，教师", "example": ""},
        {"word": "pelajaran", "pos": "n.", "phonetic": "pə-la-jar-an", "definition": "功课，课程，教育", "example": ""},
        {"word": "pengajaran", "pos": "n.", "phonetic": "pə-nga-jar-an", "definition": "教学；教训", "example": ""},

        {"word": "kerja", "pos": "n./v.", "phonetic": "kər-ja", "definition": "工作，职业；做工", "example": "kerja rumah (家庭作业/家务)"},
        {"word": "bekerja", "pos": "v.", "phonetic": "bə-kər-ja", "definition": "工作，上班", "example": "Dia bekerja di bank."},
        {"word": "mengerjakan", "pos": "v.", "phonetic": "mə-ngər-ja-kan", "definition": "执行，从事，完成", "example": ""},
        {"word": "pekerja", "pos": "n.", "phonetic": "pə-kər-ja", "definition": "工人，员工", "example": ""},
        {"word": "pekerjaan", "pos": "n.", "phonetic": "pə-kər-ja-an", "definition": "工作，行业", "example": ""},

        {"word": "tidur", "pos": "v./n.", "phonetic": "ti-dor", "definition": "睡觉，睡眠", "example": "selamat tidur (晚安)"},
        {"word": "tertidur", "pos": "v.", "phonetic": "tər-ti-dor", "definition": "睡着了，不小心睡着", "example": ""},
        {"word": "ketiduran", "pos": "n.", "phonetic": "kə-ti-dor-an", "definition": "嗜睡；睡过头", "example": ""},

        {"word": "bangun", "pos": "v.", "phonetic": "ba-ngun", "definition": "起立；起床；建立", "example": "bangun pagi (早起)"},
        {"word": "membangunkan", "pos": "v.", "phonetic": "məm-ba-ngun-kan", "definition": "叫醒；发展，建设", "example": ""},
        {"word": "bangunan", "pos": "n.", "phonetic": "ba-ngun-an", "definition": "建筑物，大楼", "example": ""},
        {"word": "pembangunan", "pos": "n.", "phonetic": "pəm-ba-ngun-an", "definition": "发展，开发", "example": ""},

        {"word": "tahu", "pos": "v./n.", "phonetic": "ta-hu", "definition": "知道，懂得；豆腐", "example": "Saya tidak tahu. (我不知道。)"},
        {"word": "mengetahui", "pos": "v.", "phonetic": "mə-ngə-ta-hu-i", "definition": "知晓，获悉", "example": ""},
        {"word": "pengetahuan", "pos": "n.", "phonetic": "pən-gə-ta-hu-an", "definition": "知识，学问", "example": ""},

        {"word": "kenal", "pos": "v.", "phonetic": "kə-nal", "definition": "认识，结识", "example": ""},
        {"word": "mengenal", "pos": "v.", "phonetic": "mə-ngə-nal", "definition": "认得，了解", "example": ""},
        {"word": "berkenalan", "pos": "v.", "phonetic": "bər-kə-nal-an", "definition": "相识，交朋友", "example": ""},
        {"word": "kenalan", "pos": "n.", "phonetic": "kə-nal-an", "definition": "相识的人，熟人", "example": ""},
        {"word": "perkenalan", "pos": "n.", "phonetic": "pər-kə-nal-an", "definition": "结识，介绍", "example": ""},

        {"word": "cakap", "pos": "v./adj.", "phonetic": "ca-kap", "definition": "说，讲话；能干的", "example": "cakap Melayu (讲马来语)"},
        {"word": "bercakap", "pos": "v.", "phonetic": "bər-ca-kap", "definition": "讲话，交谈", "example": "Bercakap perlahan-lahan."},
        {"word": "percakapan", "pos": "n.", "phonetic": "pər-ca-kap-an", "definition": "对话，谈话", "example": ""},

        {"word": "kata", "pos": "n./v.", "phonetic": "ka-ta", "definition": "词，话语；说", "example": "kata laluan (密码)"},
        {"word": "berkata", "pos": "v.", "phonetic": "bər-ka-ta", "definition": "说，言道", "example": ""},
        {"word": "mengatakan", "pos": "v.", "phonetic": "mə-nga-ta-kan", "definition": "讲明，说出", "example": ""},
        {"word": "perkataan", "pos": "n.", "phonetic": "pər-ka-ta-an", "definition": "词汇，单词", "example": ""},

        {"word": "lihat", "pos": "v.", "phonetic": "li-hat", "definition": "看，瞧", "example": ""},
        {"word": "melihat", "pos": "v.", "phonetic": "mə-li-hat", "definition": "观看，看见", "example": ""},
        {"word": "kelihatan", "pos": "adj./v.", "phonetic": "kə-li-hat-an", "definition": "看来，显现", "example": "Kelihatan cantik."},
        {"word": "penglihatan", "pos": "n.", "phonetic": "pəng-li-hat-an", "definition": "视力，视野", "example": ""},

        {"word": "dengar", "pos": "v.", "phonetic": "də-ngar", "definition": "听，闻", "example": ""},
        {"word": "mendengar", "pos": "v.", "phonetic": "mən-də-ngar", "definition": "聆听，听见", "example": "mendengar muzik"},
        {"word": "pendengar", "pos": "n.", "phonetic": "pən-də-ngar", "definition": "听众", "example": ""},
        {"word": "pendengaran", "pos": "n.", "phonetic": "pən-də-ngar-an", "definition": "听觉，听力", "example": ""},

        {"word": "rasa", "pos": "n./v.", "phonetic": "ra-sa", "definition": "感觉，味道；觉得", "example": "Saya rasa gembira."},
        {"word": "merasa", "pos": "v.", "phonetic": "mə-ra-sa", "definition": "体会，尝味", "example": ""},
        {"word": "merasakan", "pos": "v.", "phonetic": "mə-ra-sa-kan", "definition": "感到，体验到", "example": ""},
        {"word": "perasaan", "pos": "n.", "phonetic": "pə-ra-sa-an", "definition": "感情，情绪", "example": ""},

        {"word": "fikir", "pos": "v.", "phonetic": "fi-kir", "definition": "想，思考", "example": ""},
        {"word": "berfikir", "pos": "v.", "phonetic": "bər-fi-kir", "definition": "沉思，思考", "example": ""},
        {"word": "memikirkan", "pos": "v.", "phonetic": "mə-mi-kir-kan", "definition": "考量，思念", "example": ""},
        {"word": "fikiran", "pos": "n.", "phonetic": "fi-kir-an", "definition": "思想，想法", "example": ""},

        {"word": "ingat", "pos": "v.", "phonetic": "i-ngat", "definition": "记得，记起；留心", "example": "Ingat pesan saya."},
        {"word": "mengingat", "pos": "v.", "phonetic": "mə-ngi-ngat", "definition": "记住，记忆", "example": ""},
        {"word": "mengingatkan", "pos": "v.", "phonetic": "mə-ngi-ngat-kan", "definition": "提醒，警示", "example": ""},
        {"word": "peringatan", "pos": "n.", "phonetic": "pə-ri-ngat-an", "definition": "纪念；提醒，警告", "example": ""},
        {"word": "ingatan", "pos": "n.", "phonetic": "i-ngat-an", "definition": "记忆力，思念", "example": ""},

        {"word": "lupa", "pos": "v.", "phonetic": "lu-pa", "definition": "忘记，忽略", "example": "Jangan lupa! (别忘了！)"},
        {"word": "melupakan", "pos": "v.", "phonetic": "mə-lu-pa-kan", "definition": "忘却，置之脑后", "example": ""},
        {"word": "terlupa", "pos": "v.", "phonetic": "tər-lu-pa", "definition": "一时遗忘", "example": ""},

        # Adjectives
        {"word": "besar", "pos": "adj.", "phonetic": "bə-sar", "definition": "大，宏大", "example": "rumah besar"},
        {"word": "kecil", "pos": "adj.", "phonetic": "kə-chil", "definition": "小，细小", "example": ""},
        {"word": "banyak", "pos": "adj./adv.", "phonetic": "ba-nyak", "definition": "多，大量", "example": "terima kasih banyak-banyak"},
        {"word": "sedikit", "pos": "adj./adv.", "phonetic": "sə-di-kit", "definition": "少，少量，一点点", "example": ""},
        {"word": "panjang", "pos": "adj.", "phonetic": "pan-jang", "definition": "长，长久", "example": ""},
        {"word": "pendek", "pos": "adj.", "phonetic": "pen-dek", "definition": "短，矮", "example": ""},
        {"word": "tinggi", "pos": "adj.", "phonetic": "ting-gi", "definition": "高，崇高", "example": "orang tinggi"},
        {"word": "rendah", "pos": "adj.", "phonetic": "rən-dah", "definition": "低，低矮；谦虚", "example": ""},
        {"word": "cantik", "pos": "adj.", "phonetic": "chan-tek", "definition": "美丽，漂亮", "example": "bunga cantik"},
        {"word": "kacak", "pos": "adj.", "phonetic": "ka-chak", "definition": "英俊，帅气", "example": "lelaki kacak"},
        {"word": "hodoh", "pos": "adj.", "phonetic": "ho-doh", "definition": "丑陋，难看", "example": ""},
        {"word": "baik", "pos": "adj.", "phonetic": "ba-ik", "definition": "好，善良；恢复良好", "example": "orang baik"},
        {"word": "jahat", "pos": "adj.", "phonetic": "ja-hat", "definition": "邪恶，坏，狡诈", "example": ""},
        {"word": "pandai", "pos": "adj.", "phonetic": "pan-dai", "definition": "聪明，精明；擅长", "example": "pandai masak"},
        {"word": "bijak", "pos": "adj.", "phonetic": "bi-jak", "definition": "明智，睿智", "example": ""},
        {"word": "bodoh", "pos": "adj.", "phonetic": "bo-doh", "definition": "愚蠢，笨", "example": ""},
        {"word": "rajin", "pos": "adj.", "phonetic": "ra-jin", "definition": "勤奋，勤劳", "example": "murid rajin"},
        {"word": "malas", "pos": "adj.", "phonetic": "ma-las", "definition": "懒惰", "example": ""},
        {"word": "senang", "pos": "adj.", "phonetic": "sə-nang", "definition": "容易，简单；舒心", "example": "soalan senang"},
        {"word": "mudah", "pos": "adj.", "phonetic": "mu-dah", "definition": "容易，简便", "example": ""},
        {"word": "susah", "pos": "adj.", "phonetic": "su-sah", "definition": "困难，难办；贫苦", "example": ""},
        {"word": "sukar", "pos": "adj.", "phonetic": "su-kar", "definition": "艰巨，困难", "example": ""},
        {"word": "sejuk", "pos": "adj.", "phonetic": "sə-jok", "definition": "冷，凉爽", "example": "air sejuk"},
        {"word": "bersih", "pos": "adj.", "phonetic": "bər-seh", "definition": "干净，清洁", "example": ""},
        {"word": "kotor", "pos": "adj.", "phonetic": "ko-tor", "definition": "肮脏，脏", "example": ""},
        {"word": "murah", "pos": "adj.", "phonetic": "mu-rah", "definition": "便宜，低廉", "example": "harga murah"},
        {"word": "mahal", "pos": "adj.", "phonetic": "ma-hal", "definition": "昂贵，贵", "example": "barang mahal"},
        {"word": "cepat", "pos": "adj./adv.", "phonetic": "chə-pat", "definition": "快，迅速", "example": "cepat sikit (快一点)"},
        {"word": "pantas", "pos": "adj./adv.", "phonetic": "pan-tas", "definition": "敏捷，迅速", "example": ""},
        {"word": "lambat", "pos": "adj./adv.", "phonetic": "lam-bat", "definition": "慢，迟到", "example": "Kenapa lambat?"},
        {"word": "perlahan", "pos": "adj./adv.", "phonetic": "pər-la-han", "definition": "缓慢，轻声", "example": "Jalan perlahan-lahan."},
        {"word": "baharu", "pos": "adj.", "phonetic": "ba-ha-ru", "definition": "新，崭新", "example": "tahun baharu (新年)"},
        {"word": "baru", "pos": "adj./adv.", "phonetic": "ba-ru", "definition": "新；刚才", "example": "baru sampai (刚到)"},
        {"word": "lama", "pos": "adj.", "phonetic": "la-ma", "definition": "旧的，古老；长久", "example": "kawan lama (老朋友)"},
        {"word": "tua", "pos": "adj.", "phonetic": "tu-a", "definition": "年老，老", "example": "orang tua (老人/父母)"},
        {"word": "muda", "pos": "adj.", "phonetic": "mu-da", "definition": "年轻", "example": "orang muda"},
        {"word": "sedap", "pos": "adj.", "phonetic": "sə-dap", "definition": "美味，好吃的；舒适", "example": "Makanan ini sangat sedap."},
        {"word": "lazat", "pos": "adj.", "phonetic": "la-zat", "definition": "可口，极美味", "example": ""},
        {"word": "manis", "pos": "adj.", "phonetic": "ma-nis", "definition": "甜的；甜美", "example": ""},
        {"word": "masin", "pos": "adj.", "phonetic": "ma-sin", "definition": "咸的", "example": ""},
        {"word": "masam", "pos": "adj.", "phonetic": "ma-sam", "definition": "酸的", "example": ""},
        {"word": "pahit", "pos": "adj.", "phonetic": "pa-hit", "definition": "苦的", "example": ""},
        {"word": "pedas", "pos": "adj.", "phonetic": "pə-das", "definition": "辣的", "example": "sambal pedas"},

        # Numbers & Time
        {"word": "satu", "pos": "num.", "phonetic": "sa-tu", "definition": "一 (1)", "example": ""},
        {"word": "dua", "pos": "num.", "phonetic": "du-a", "definition": "二 (2)", "example": ""},
        {"word": "tiga", "pos": "num.", "phonetic": "ti-ga", "definition": "三 (3)", "example": ""},
        {"word": "empat", "pos": "num.", "phonetic": "əm-pat", "definition": "四 (4)", "example": ""},
        {"word": "lima", "pos": "num.", "phonetic": "li-ma", "definition": "五 (5)", "example": ""},
        {"word": "enam", "pos": "num.", "phonetic": "ə-nam", "definition": "六 (6)", "example": ""},
        {"word": "tujuh", "pos": "num.", "phonetic": "tu-joh", "definition": "七 (7)", "example": ""},
        {"word": "lapan", "pos": "num.", "phonetic": "la-pan", "definition": "八 (8)", "example": ""},
        {"word": "sembilan", "pos": "num.", "phonetic": "səm-bi-lan", "definition": "九 (9)", "example": ""},
        {"word": "sepuluh", "pos": "num.", "phonetic": "sə-pu-loh", "definition": "十 (10)", "example": ""},
        {"word": "sebelas", "pos": "num.", "phonetic": "sə-bə-las", "definition": "十一 (11)", "example": ""},
        {"word": "dua puluh", "pos": "num.", "phonetic": "", "definition": "二十 (20)", "example": ""},
        {"word": "seratus", "pos": "num.", "phonetic": "sə-ra-tus", "definition": "一百 (100)", "example": ""},
        {"word": "seribu", "pos": "num.", "phonetic": "sə-ri-bu", "definition": "一千 (1000)", "example": ""},
        {"word": "sejuta", "pos": "num.", "phonetic": "sə-ju-ta", "definition": "一百万 (1,000,000)", "example": ""},
        {"word": "kosong", "pos": "num./adj.", "phonetic": "ko-song", "definition": "零；空的", "example": "air kosong (白开水)"},
        {"word": "hari", "pos": "n.", "phonetic": "ha-ri", "definition": "天，日子", "example": "hari ini (今天)"},
        {"word": "hari ini", "pos": "n.", "phonetic": "", "definition": "今天", "example": ""},
        {"word": "semalam", "pos": "n./adv.", "phonetic": "sə-ma-lam", "definition": "昨天；昨晚", "example": ""},
        {"word": "kelmarin", "pos": "n./adv.", "phonetic": "kəl-ma-rin", "definition": "前天", "example": ""},
        {"word": "esok", "pos": "n./adv.", "phonetic": "e-sok", "definition": "明天", "example": "Jumpa esok. (明天见。)"},
        {"word": "lusa", "pos": "n./adv.", "phonetic": "lu-sa", "definition": "后天", "example": ""},
        {"word": "pagi", "pos": "n.", "phonetic": "pa-gi", "definition": "早晨，早上", "example": ""},
        {"word": "tengah hari", "pos": "n.", "phonetic": "", "definition": "中午", "example": ""},
        {"word": "petang", "pos": "n.", "phonetic": "pə-tang", "definition": "下午，傍晚", "example": ""},
        {"word": "malam", "pos": "n.", "phonetic": "ma-lam", "definition": "夜晚，晚上", "example": ""},
        {"word": "minggu", "pos": "n.", "phonetic": "ming-gu", "definition": "星期，周", "example": "minggu depan (下周)"},
        {"word": "bulan", "pos": "n.", "phonetic": "bu-lan", "definition": "月份；月亮", "example": "bulan depan (下个月)"},
        {"word": "tahun", "pos": "n.", "phonetic": "ta-hon", "definition": "年，岁", "example": "tahun ini (今年)"},
        {"word": "jam", "pos": "n.", "phonetic": "jam", "definition": "小时；钟表", "example": "pukul berapa (几点了)"},
        {"word": "minit", "pos": "n.", "phonetic": "mi-nit", "definition": "分钟", "example": ""},
        {"word": "saat", "pos": "n.", "phonetic": "sa-at", "definition": "秒；时刻", "example": ""},

        # Places & Society
        {"word": "rumah", "pos": "n.", "phonetic": "ru-mah", "definition": "房子，家", "example": "balik rumah (回家)"},
        {"word": "sekolah", "pos": "n.", "phonetic": "sə-ko-lah", "definition": "学校", "example": ""},
        {"word": "universiti", "pos": "n.", "phonetic": "u-ni-vər-si-ti", "definition": "大学", "example": ""},
        {"word": "hospital", "pos": "n.", "phonetic": "hos-pi-tal", "definition": "医院", "example": ""},
        {"word": "klinik", "pos": "n.", "phonetic": "kli-nik", "definition": "诊所", "example": ""},
        {"word": "kedai", "pos": "n.", "phonetic": "kə-dai", "definition": "商店，铺子", "example": "kedai kopi (咖啡店)"},
        {"word": "restoran", "pos": "n.", "phonetic": "res-to-ran", "definition": "餐馆，饭店", "example": ""},
        {"word": "pasar", "pos": "n.", "phonetic": "pa-sar", "definition": "市场，集市", "example": "pasar malam (夜市)"},
        {"word": "pasar malam", "pos": "n.", "phonetic": "", "definition": "夜市", "example": ""},
        {"word": "bank", "pos": "n.", "phonetic": "beng-k", "definition": "银行", "example": ""},
        {"word": "pejabat", "pos": "n.", "phonetic": "pə-ja-bat", "definition": "办公室，办事处", "example": "pejabat pos (邮局)"},
        {"word": "pejabat pos", "pos": "n.", "phonetic": "", "definition": "邮局", "example": ""},
        {"word": "stesen", "pos": "n.", "phonetic": "ste-sen", "definition": "车站，站点", "example": "stesen bas (巴士站)"},
        {"word": "lapangan terbang", "pos": "n.", "phonetic": "", "definition": "机场，飞机场", "example": ""},
        {"word": "tandas", "pos": "n.", "phonetic": "tan-das", "definition": "厕所，洗手间", "example": "Di mana tandas?"},
        {"word": "masjid", "pos": "n.", "phonetic": "mas-jid", "definition": "清真寺", "example": ""},
        {"word": "kuil", "pos": "n.", "phonetic": "ku-il", "definition": "庙宇，印度庙", "example": ""},
        {"word": "gereja", "pos": "n.", "phonetic": "gə-re-ja", "definition": "教堂", "example": ""},
        {"word": "negara", "pos": "n.", "phonetic": "nə-ga-ra", "definition": "国家", "example": ""},
        {"word": "bandar", "pos": "n.", "phonetic": "ban-dar", "definition": "城市，市镇", "example": ""},
        {"word": "kampung", "pos": "n.", "phonetic": "kam-pong", "definition": "乡村，村庄，家乡", "example": "balik kampung (回乡)"},
        {"word": "kereta", "pos": "n.", "phonetic": "kə-re-ta", "definition": "汽车，车辆", "example": "kereta api (火车)"},
        {"word": "kereta api", "pos": "n.", "phonetic": "", "definition": "火车", "example": ""},
        {"word": "bas", "pos": "n.", "phonetic": "bas", "definition": "公共汽车，巴士", "example": ""},
        {"word": "teksi", "pos": "n.", "phonetic": "tek-si", "definition": "出租车，德士", "example": ""},
        {"word": "motosikal", "pos": "n.", "phonetic": "mo-to-si-kal", "definition": "摩托车", "example": ""},
        {"word": "basikal", "pos": "n.", "phonetic": "ba-si-kal", "definition": "自行车，脚踏车", "example": ""},
        {"word": "kapal terbang", "pos": "n.", "phonetic": "", "definition": "飞机", "example": ""},
        {"word": "kapal", "pos": "n.", "phonetic": "ka-pal", "definition": "轮船，大船", "example": ""},
        {"word": "bot", "pos": "n.", "phonetic": "bot", "definition": "小艇，船", "example": ""},
    ]
    return ms_list


def get_curated_en_words():
    """
    Returns curated English entries for essential lookups, including homographs like air.
    """
    en_list = [
        {"word": "air", "display": "air", "pos": "n./v.", "phonetic": "/eə(r)/", "definition": "n. 空气，大气；天空；空运；神气\nv. 通风，晾干；公开发表", "example": "fresh air (新鲜空气)"},
        {"word": "butterscotch", "display": "butterscotch", "pos": "n.", "phonetic": "/ˈbʌtəskɒtʃ/", "definition": "n. 奶油糖果，黄油糖果；奶油色", "example": "butterscotch ice cream (奶油糖果冰淇淋)"},
        {"word": "hello", "display": "hello", "pos": "int./n.", "phonetic": "/həˈləʊ/", "definition": "int. 喂，你好\nn. 问候，招呼", "example": "Hello, world!"},
        {"word": "world", "display": "world", "pos": "n.", "phonetic": "/wɜːld/", "definition": "n. 世界；地球；世间；领域", "example": "around the world"},
        {"word": "dictionary", "display": "dictionary", "pos": "n.", "phonetic": "/ˈdɪkʃənri/", "definition": "n. 词典，字典", "example": "an English dictionary"},
        {"word": "language", "display": "language", "pos": "n.", "phonetic": "/ˈlæŋɡwɪdʒ/", "definition": "n. 语言；言语；措辞", "example": "foreign language"},
        {"word": "translate", "display": "translate", "pos": "v.", "phonetic": "/trænzˈleɪt/", "definition": "v. 翻译；转变，转化", "example": "translate into Chinese"},
        {"word": "translation", "display": "translation", "pos": "n.", "phonetic": "/trænzˈleɪʃn/", "definition": "n. 翻译；译文，译本", "example": ""},
        {"word": "search", "display": "search", "pos": "v./n.", "phonetic": "/sɜːtʃ/", "definition": "v. 搜寻，搜查，检索\nn. 搜查，探寻", "example": "search engine (搜索引擎)"},
        {"word": "offline", "display": "offline", "pos": "adj./adv.", "phonetic": "/ˌɒfˈlaɪn/", "definition": "adj./adv. 离线的，未连线的", "example": "offline dictionary"},
        {"word": "online", "display": "online", "pos": "adj./adv.", "phonetic": "/ˈɒnlaɪn/", "definition": "adj./adv. 在线的，连网的", "example": "online search"},
        {"word": "favorite", "display": "favorite", "pos": "adj./n.", "phonetic": "/ˈfeɪvərɪt/", "definition": "adj. 最喜爱的\nn. 最喜爱的人或物；收藏夹", "example": "add to favorites (添加到收藏)"},
        {"word": "history", "display": "history", "pos": "n.", "phonetic": "/ˈhɪstri/", "definition": "n. 历史；历史学；经历，履历", "example": "search history (搜索历史)"},
        {"word": "word", "display": "word", "pos": "n./v.", "phonetic": "/wɜːd/", "definition": "n. 单词，词；言语；诺言\nv. 措辞，表达", "example": "new words (生词)"},
        {"word": "meaning", "display": "meaning", "pos": "n.", "phonetic": "/ˈmiːnɪŋ/", "definition": "n. 含义，意义；意图", "example": "the meaning of life"},
        {"word": "pronunciation", "display": "pronunciation", "pos": "n.", "phonetic": "/prəˌnʌnsiˈeɪʃn/", "definition": "n. 发音，读法", "example": "correct pronunciation"},
        {"word": "speak", "display": "speak", "pos": "v.", "phonetic": "/spiːk/", "definition": "v. 说话，讲；演说；讲某种语言", "example": "speak English / speak Malay"},
        {"word": "copy", "display": "copy", "pos": "v./n.", "phonetic": "/ˈkɒpi/", "definition": "v. 复制，抄写；模仿\nn. 副本，复制品", "example": "copy to clipboard"},
        {"word": "share", "display": "share", "pos": "v./n.", "phonetic": "/ʃeə(r)/", "definition": "v. 分享，分担；共有\nn. 份额，股份", "example": ""},
        {"word": "setting", "display": "setting", "pos": "n.", "phonetic": "/ˈsetɪŋ/", "definition": "n. 设置，调节；背景，环境", "example": "app settings (应用设置)"},
        {"word": "clear", "display": "clear", "pos": "adj./v.", "phonetic": "/klɪə(r)/", "definition": "adj. 清晰的；晴朗的；清楚的\nv. 清除，清理", "example": "clear all history (清除所有历史)"},
    ]
    return en_list
